version: 2
updates:
  - &default_update
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: "scope"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    reviewers:
      - thomasvincent

  - package-ecosystem: pip
    directory: "/"
    <<: *default_update

  - package-ecosystem: "github-actions"
    directory: "/"
    <<: *default_update

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    <<: *default_update

  - package-ecosystem: "gomod"
    directory: "/"
    <<: *default_update

  - package-ecosystem: "docker"
    directory: "/"
    <<: *default_update

  - package-ecosystem: "npm"
    directory: "/"
    <<: *default_update
